# -*- coding: utf-8 -*-
"""Module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIEpspLB4usBxRyxqaqpgbuHs9pprU2o
"""

def add(*args):
  s=0
  for i in args:
    s+=i
  return s

def checkIfNumeric(*args):
  for i in args:
    if isinstance(i,(int,float)):
      return True
  return False